require 'nasta/dummy/success_report'
require 'nasta/dummy/error_report'
require 'nasta/new_relic/error_rate_martinus'
require 'nasta/new_relic/error_rate_admin'
require 'nasta/new_relic/error_rate_background_jobs'
require 'nasta/new_relic/response_time_pda'
