name: deploy function to lambda
on: [push]
jobs:
    deploy_source:
        name: deploy lambda from source
        runs-on: ubuntu-latest
        steps:
            -   name: checkout source code
                uses: actions/checkout@v1
            -   name: default deploy
        -   name: Zip function
            run: bin/build-zip
        -   name: AWS Lambda FunctionCode Update
            uses: taotao2345/aws-lambda-updatecode@v1.0.0
            env:
                AWS_REGION: ${{ secrets.AWS_REGION }}
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            with:
                function_name: TodoChangeName
                zip_file: nasta-backend.zip